### ISSUE TITLE
Doesn't work for us.

### ISSUE THREAD

**Issue by Alevhovic** [LuaDeldu/esx_advanced_holdup#5]
Nothing appears (marker, not if ...).
- no errors in cmd 
- no errors in FiveM F8 ...

The resource is start after esx_policejob of course.

Test with esx_holdup & without. Doesn't work at all for us.

**Comment by delduwaht** [comment]
Markers only appear if there are **X cops connected** (related to the PoliceRequired in the config.lua file) and if you have a **gun on your hand**.
